# Generated by Django 2.1 on 2018-09-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decoaire_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
